services:
  app:
    user: "1000:1000" 
    build:
      context: ./docker/app
    container_name: catalogo_app
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: catalogo_web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: postgres:16-alpine
    container_name: catalogo_db
    environment:
      POSTGRES_DB: catalogo
      POSTGRES_USER: catalogo
      POSTGRES_PASSWORD: catalogo123
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
